version: '2'
services:
  web:
    build: .
    command: python3 webform/mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: rz01
    ports:
      - '0.0.0.0:8080:6379'
